{% set version = "1.14.7-1" %}
{% set sha256 = "68b6b424fda14f327baa17aa1a2417616b783851150561af13670b03e0f8e51d" %}

package:
  name: ros-roslib
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/ros-gbp/ros-release/archive/release/melodic/roslib/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('ros-roslib', 'x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python
    - catkin_pkg
    - ros-rospack
    - boost-cpp
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python
    - ros-catkin
    - ros-rospack
    - rospkg
    - ros-environment

test:
  requires:
    - rospkg
  commands:
    - export ROS_ROOT=$PREFIX && python -c "import rospkg;s = rospkg.RosPack();ret = s.get_path('roslib');print(ret)"

about:
  home: http://ros.org/wiki/roslib
  summary: |
    Base dependencies and support libraries for ROS.
  description: |
    Base dependencies and support libraries for ROS. roslib contains many of the
    common data structures and tools that are shared across ROS client library
    implementations.
  license: BSD-3-Clause
  license_file: include/ros/package.h

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
